### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by benhayes36** [Jime86/DonationLogger#3]
Getting the following issue while using your DonationLogger:

(node:3272) DeprecationWarning: TextChannel#sendEmbed: use TextChannel#send instead

**Comment by danilose** [comment]
I solved this here #2 
But still waiting my pull request be merged

**Comment by Jime86** [comment]
Sorry about that. this project has been silently running in the back ground for so long i forgot it existed. I approved the pull request.
